### ISSUE TITLE
数据一多内存泄漏

### ISSUE THREAD

**Issue by redwolf1996** [curry-trooper/tank-vue3-seamless-scroll#1]
数据多的时候内存 1s 增加100m 很快就被榨干了 作者有考虑 类似虚拟列表的方案吗

**Comment by fanqie** [comment]
大概有多少数据

**Comment by fanqie** [comment]
- 经自查，插件自身不存在内存泄漏问题，目前可以确认，由于您的工程渲染第三方组件轮询数量过大导致内存溢出，资源过载，这个问题目前的版本无法支持
- 未来版本会考虑虚拟化的问题，用于大数据滚动展示，实现原理技术路径不同，会以新组件形式提供使用
