### ISSUE TITLE
项目打包后加载问题

### ISSUE THREAD

**Issue by Canees** [curry-trooper/tank-vue3-seamless-scroll#3]
![image](https://github.com/fanqie/tank-vue3-seamless-scroll/assets/40012261/a5472707-847d-426c-9467-e94cdaede742)
打包后，出现报错

**Comment by fanqie** [comment]
__scopeId 是vue2 的特征，请问您是在vue2的环境中吗？

**Comment by Canees** [comment]
> __scopeId 是vue2 的特征，请问您是在vue2的环境中吗？

没有在vue2中使用，vue3.3.11 vite5.0.8
<img width="465" alt="image" src="https://github.com/fanqie/tank-vue3-seamless-scroll/assets/40012261/88e7f62d-0431-4ee9-94b7-0fb2b444efc0">

**Comment by fanqie** [comment]
目前看来，我新提交的测试 ~/example/ 工程与您使用的依赖版本均一致，可以正常构建打包，也可以正常运行，以下是我的测试过程：
![image](https://github.com/fanqie/tank-vue3-seamless-scroll/assets/466966/046e1a22-7c4c-413a-8b0c-d8667b087dfe)
![image](https://github.com/fanqie/tank-vue3-seamless-scroll/assets/466966/8a238312-2d8d-4640-9b22-567b5f8cb61f)
![image](https://github.com/fanqie/tank-vue3-seamless-scroll/assets/466966/8b9b299f-c02e-4ff8-b0ca-7af78c060289)
您也可以拉源码单独跑一下example
```bash
# cd example/
# npm install
# npm run dev
# npm run build
```
